name: 🚀 Deploy to Scaleway

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📦 Checkout code
      uses: actions/checkout@v3
      
    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: 📥 Install dependencies
      run: npm ci
      
    - name: 🔨 Build application
      run: npm run build
      
    - name: 🚀 Deploy to Scaleway
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SCALEWAY_HOST }}
        username: ${{ secrets.SCALEWAY_USER }}
        password: ${{ secrets.SCALEWAY_PASSWORD }}
        script: |
          cd /var/www/av-concept-projects
          
          # Sauvegarder la version actuelle
          cp -r dist dist_backup_$(date +%Y%m%d_%H%M%S)
          
          # Récupérer les dernières modifications
          git pull origin main
          
          # Installer les dépendances
          npm install
          
          # Rebuilder l'application
          npm run build
          
          # Redémarrer nginx
          systemctl restart nginx
          
          # Vérifier le statut
          systemctl status nginx --no-pager -l
          
          echo "🎉 Déploiement terminé avec succès !"
